# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      
      - name: Install gitbook-cli
        run: npm install -g gitbook-cli
        
      - name: Install Dependent Node Pkgs
        run: gitbook install
      
      # Runs a single command using the runners shell
      - name: Build
        run: chmod +x ./build.sh && ./build.sh

      # Runs a set of commands using the runners shell
      - name: Commit and Push
        run: |-
          git config --global user.email "lovelvqingqing@gmail.com"
          git config --global user.name "Dable Lv"
          git add -A
          git commit -m "build:auto build and deploy"
          git push
